name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: lein deps

    - name: Run Eastwood (linter)
      run: lein eastwood

    - name: Run cljfmt (formatter)
      run: lein cljfmt check

    - name: Run tests
      run: lein test
